name: Java-Golang

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 17-ea]
        go: ['1.16', '1.17', '1.19']
      # Run all tests even if one fails
      fail-fast: false
    name: Test with JDK ${{ matrix.java }}, Go ${{ matrix.go }}, ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Test
        run: |
          make test
